# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    firewalls:
        secured_area:
            pattern: ^/
            anonymous: ~
            form_login:
              login_path: login
              check_path: login_check
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/auth, roles: ROLE_ADMIN }
        - { path: ^/auth$, roles: ROLE_ADMIN }
    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory:
            memory:
              users:
                ruben: {password: nieto, roles: 'ROLE_ADMIN'}

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext


